In [207]:
import pandas as pd
import numpy as np

In [208]:
df = pd.read_csv("matches.csv")
df.head()

id  season        city       date                  team1  \
0   1    2008   Bangalore  4/18/2008  Kolkata Knight Riders   
1   2    2008  Chandigarh  4/19/2008    Chennai Super Kings   
2   3    2008       Delhi  4/19/2008       Rajasthan Royals   
3   4    2008      Mumbai  4/20/2008         Mumbai Indians   
4   5    2008     Kolkata  4/20/2008        Deccan Chargers   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1              Kings XI Punjab          Chennai Super Kings           bat   
2             Delhi Daredevils             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4        Kolkata Knight Riders              Deccan Chargers           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0        Kolkata Knight Riders          140   
1  normal           0          Chennai Super Kings           33   
2  normal           0             Delhi Daredevils            0   
3  normal           0  Royal Challengers Bangalore            0   
4  normal           0        Kolkata Knight Riders            0   

   win_by_wickets player_of_match                                       venue  \
0               0     BB McCullum                       M Chinnaswamy Stadium   
1               0      MEK Hussey  Punjab Cricket Association Stadium, Mohali   
2               9     MF Maharoof                            Feroz Shah Kotla   
3               5      MV Boucher                            Wankhede Stadium   
4               5       DJ Hussey                                Eden Gardens   

     umpire1         umpire2  umpire3  
0  Asad Rauf     RE Koertzen      NaN  
1  MR Benson      SL Shastri      NaN  
2  Aleem Dar  GA Pratapkumar      NaN  
3   SJ Davis       DJ Harper      NaN  
4  BF Bowden     K Hariharan      NaN

In [209]:
a = df.groupby('season')
for i, j  in a:
    print(i)

2008
2009
2010
2011
2012
2013
2014
2015
2016


In [210]:
df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [211]:
df.replace(['Mumbai Indians','Kolkata Knight Riders','Royal Challengers Bangalore','Deccan Chargers','Chennai Super Kings',
                 'Rajasthan Royals','Delhi Daredevils','Gujarat Lions','Kings XI Punjab',
                 'Sunrisers Hyderabad','Rising Pune Supergiants','Kochi Tuskers Kerala','Pune Warriors']
                ,[1,2,3,4,5,6,7,8,9,10,11,12,13],inplace=True)
df

id  season        city       date  team1  team2  toss_winner  \
0      1    2008   Bangalore  4/18/2008      2      3            3   
1      2    2008  Chandigarh  4/19/2008      5      9            5   
2      3    2008       Delhi  4/19/2008      6      7            6   
3      4    2008      Mumbai  4/20/2008      1      3            1   
4      5    2008     Kolkata  4/20/2008      4      2            4   
..   ...     ...         ...        ...    ...    ...          ...   
572  573    2016      Raipur  5/22/2016      7      3            3   
573  574    2016   Bangalore  5/24/2016      8      3            3   
574  575    2016       Delhi  5/25/2016     10      2            2   
575  576    2016       Delhi  5/27/2016      8     10           10   
576  577    2016   Bangalore  5/29/2016     10      3           10   

    toss_decision  result  dl_applied  winner  win_by_runs  win_by_wickets  \
0           field  normal           0     2.0          140               0   
1             bat  normal           0     5.0           33               0   
2             bat  normal           0     7.0            0               9   
3             bat  normal           0     3.0            0               5   
4             bat  normal           0     2.0            0               5   
..            ...     ...         ...     ...          ...             ...   
572         field  normal           0     3.0            0               6   
573         field  normal           0     3.0            0               4   
574         field  normal           0    10.0           22               0   
575         field  normal           0    10.0            0               4   
576           bat  normal           0    10.0            8               0   

    player_of_match                                             venue  \
0       BB McCullum                             M Chinnaswamy Stadium   
1        MEK Hussey        Punjab Cricket Association Stadium, Mohali   
2       MF Maharoof                                  Feroz Shah Kotla   
3        MV Boucher                                  Wankhede Stadium   
4         DJ Hussey                                      Eden Gardens   
..              ...                                               ...   
572         V Kohli  Shaheed Veer Narayan Singh International Stadium   
573  AB de Villiers                             M Chinnaswamy Stadium   
574    MC Henriques                                  Feroz Shah Kotla   
575       DA Warner                                  Feroz Shah Kotla   
576     BCJ Cutting                             M Chinnaswamy Stadium   

             umpire1          umpire2  umpire3  
0          Asad Rauf      RE Koertzen      NaN  
1          MR Benson       SL Shastri      NaN  
2          Aleem Dar   GA Pratapkumar      NaN  
3           SJ Davis        DJ Harper      NaN  
4          BF Bowden      K Hariharan      NaN  
..               ...              ...      ...  
572   A Nand Kishore     BNJ Oxenford      NaN  
573     AK Chaudhary  HDPK Dharmasena      NaN  
574        M Erasmus    C Shamshuddin      NaN  
575        M Erasmus        CK Nandan      NaN  
576  HDPK Dharmasena     BNJ Oxenford      NaN  

[577 rows x 18 columns]

In [212]:
df['city'].fillna('na', inplace = True)
df['date'].fillna(0, inplace = True)
df['team1'].fillna('na', inplace = True)
df['team2'].fillna('na', inplace = True)
df['toss_winner'].fillna('na', inplace = True)
df['toss_decision'].fillna('na', inplace = True)
df['venue'].fillna(0, inplace = True)
df['result'].fillna('no result', inplace = True)
df['winner'].fillna('na', inplace = True)
df['player_of_match'].fillna('no player', inplace = True)
df['toss_decision'].fillna('na', inplace = True)
df['umpire1'].fillna('no umpire1', inplace = True)
df['umpire2'].fillna('no umpire2', inplace = True)
df['umpire3'].fillna('no umpire3', inplace = True)
df['dl_applied'].fillna(0, inplace = True)
df['win_by_runs'].fillna(0, inplace = True)
df['win_by_wickets'].fillna(0, inplace = True)
df

id  season        city       date  team1  team2  toss_winner  \
0      1    2008   Bangalore  4/18/2008      2      3            3   
1      2    2008  Chandigarh  4/19/2008      5      9            5   
2      3    2008       Delhi  4/19/2008      6      7            6   
3      4    2008      Mumbai  4/20/2008      1      3            1   
4      5    2008     Kolkata  4/20/2008      4      2            4   
..   ...     ...         ...        ...    ...    ...          ...   
572  573    2016      Raipur  5/22/2016      7      3            3   
573  574    2016   Bangalore  5/24/2016      8      3            3   
574  575    2016       Delhi  5/25/2016     10      2            2   
575  576    2016       Delhi  5/27/2016      8     10           10   
576  577    2016   Bangalore  5/29/2016     10      3           10   

    toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0           field  normal           0      2          140               0   
1             bat  normal           0      5           33               0   
2             bat  normal           0      7            0               9   
3             bat  normal           0      3            0               5   
4             bat  normal           0      2            0               5   
..            ...     ...         ...    ...          ...             ...   
572         field  normal           0      3            0               6   
573         field  normal           0      3            0               4   
574         field  normal           0     10           22               0   
575         field  normal           0     10            0               4   
576           bat  normal           0     10            8               0   

    player_of_match                                             venue  \
0       BB McCullum                             M Chinnaswamy Stadium   
1        MEK Hussey        Punjab Cricket Association Stadium, Mohali   
2       MF Maharoof                                  Feroz Shah Kotla   
3        MV Boucher                                  Wankhede Stadium   
4         DJ Hussey                                      Eden Gardens   
..              ...                                               ...   
572         V Kohli  Shaheed Veer Narayan Singh International Stadium   
573  AB de Villiers                             M Chinnaswamy Stadium   
574    MC Henriques                                  Feroz Shah Kotla   
575       DA Warner                                  Feroz Shah Kotla   
576     BCJ Cutting                             M Chinnaswamy Stadium   

             umpire1          umpire2     umpire3  
0          Asad Rauf      RE Koertzen  no umpire3  
1          MR Benson       SL Shastri  no umpire3  
2          Aleem Dar   GA Pratapkumar  no umpire3  
3           SJ Davis        DJ Harper  no umpire3  
4          BF Bowden      K Hariharan  no umpire3  
..               ...              ...         ...  
572   A Nand Kishore     BNJ Oxenford  no umpire3  
573     AK Chaudhary  HDPK Dharmasena  no umpire3  
574        M Erasmus    C Shamshuddin  no umpire3  
575        M Erasmus        CK Nandan  no umpire3  
576  HDPK Dharmasena     BNJ Oxenford  no umpire3  

[577 rows x 18 columns]

In [242]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['city','toss_decision','venue']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i])
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


team1  team2  city  toss_decision  toss_winner  venue winner
0        2      3     2              1            3     14      2
1        5      9     6              0            5     22      5
2        6      7     9              0            6      8      7
3        1      3    21              0            1     34      3
4        4      2    20              0            4      7      2
..     ...    ...   ...            ...          ...    ...    ...
572      7      3    25              1            3     27      3
573      8      3     2              1            3     14      3
574     10      2     9              1            2      8     10
575      8     10     9              1           10      8     10
576     10      3     2              0           10     14     10

[577 rows x 7 columns]

In [255]:
df.replace('na',0,inplace=True)

In [256]:
x = df[[ 'city', 'team1', 'team2','toss_decision', 'venue']]
y = df.winner
df.head()

team1  team2  city  toss_decision  toss_winner  venue  winner
0      2      3     2              1            3     14     2.0
1      5      9     6              0            5     22     5.0
2      6      7     9              0            6      8     7.0
3      1      3    21              0            1     34     3.0
4      4      2    20              0            4      7     2.0

In [257]:
df = df[['team1','team2','city','toss_decision','toss_winner','venue','winner']]
df.head(2)

team1  team2  city  toss_decision  toss_winner  venue  winner
0      2      3     2              1            3     14     2.0
1      5      9     6              0            5     22     5.0

In [265]:
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)
x_train

city  team1  team2  toss_decision  venue
324    13     10     13              1     23
516    20      1      5              1      7
567    17      2      8              1      9
0       2      2      3              1     14
311    10      5      9              1     10
..    ...    ...    ...            ...    ...
248     7      5      1              1     15
90     12      1      7              0      2
152    15      9      6              0     26
511     2      7      3              1     14
2       9      6      7              0      8

[403 rows x 5 columns]

In [281]:
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

In [282]:
dt = tree.DecisionTreeClassifier()
dt.fit(x_train, y_train)
dt.score(x_test, y_test)


0.39080459770114945

In [283]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)


0.2682028262267644

In [284]:
sv = svm.SVC(kernel='rbf', C=1)
sv.fit(x_train, y_train)
sv.score(x_test, y_test)

0.43103448275862066

In [295]:
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.47701149425287354

In [314]:
def get_score(model,x_train,x_test,y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [336]:
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
X = df.drop(df[['winner']], axis = 'columns')
y  = df.winner
y

0       2.0
1       5.0
2       7.0
3       3.0
4       2.0
       ... 
572     3.0
573     3.0
574    10.0
575    10.0
576    10.0
Name: winner, Length: 577, dtype: float64

In [337]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr, data, target)

array([0.35109167, 0.45820264, 0.25172474, 0.38735061, 0.43486791])

In [318]:
cross_val_score(dt, data, target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


array([0.38793103, 0.43103448, 0.3826087 , 0.47826087, 0.52173913])

In [319]:
cross_val_score(sv, data, target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


array([0.29310345, 0.34482759, 0.39130435, 0.3826087 , 0.33043478])

In [320]:
cross_val_score(rf, data, target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


array([0.47413793, 0.47413793, 0.39130435, 0.43478261, 0.54782609])